# Site settings
title: Bitcamp 2016
email: hello@bit.camp
baseurl: ""
url: "http://2016.2016.bit.camp"
typeform_url: "/register"
content_home_dir: "content_blocks_html"
sponsor_logo_dir: "/img/sponsor-logos/"
speaker_photo_dir: "/img/speaker-photos/"
colorwar_judge_photo_dir: "/img/cw-judge-photos/"
registration_status: "closed"
